# PATH
export PATH="$HOME/.local/bin:/opt/homebrew/opt/openssl@3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

# Editor
export EDITOR=nvim
alias vim=nvim
alias vi=nvim

# Aliases
alias ls="ls -GpF"
alias gs="git status"
alias gco="git checkout"
alias grep="grep --color=auto"

# Prompt
export PS1="\[\e[1;37m\]\W\$\[\e[0m\] "
export CLICOLOR=1

# History (unlimited, shared across sessions)
export HISTSIZE=-1
export HISTFILESIZE=-1
shopt -s histappend
shopt -s cmdhist
shopt -s lithist
PROMPT_COMMAND="history -a; history -c; history -r${PROMPT_COMMAND:+; $PROMPT_COMMAND}"

# Tools
command -v rbenv &>/dev/null && eval "$(rbenv init -)"
source "$HOME/.cargo/env"
