alias vim=nvim
alias vi=nvim
alias ls="ls -GpF"
alias gs="git status"
alias gco="git checkout"
alias docker='docker-machine start > /dev/null && eval $(docker-machine env) && unalias docker && docker'

export PS1="\[\e[1;37m\]\W\$\[\e[0m\] "
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export EDITOR=nvim
export VMAIL_VIM=nvim

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

export HISTSIZE=""

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if [ -f $HOME/.profile ]; then
  source $HOME/.profile
fi

export PATH="/usr/local/sbin:$PATH"

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
